apiVersion: v1
kind: Service
metadata:
  name: loan-backend-service
  labels:
    app: loan-backend
spec:
  selector:
    app: loan-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP